# Generated by Django 2.2 on 2021-07-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sec',
        #     name='orientation',
        # ),
        migrations.AddField(
            model_name='sec',
            name='built',
            field=models.DateField(default='2021-01-01'),
            preserve_default=False,
        ),
    ]
