# Generated by Django 2.2 on 2021-07-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20210720_1520'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sec',
        #     name='built',
        # ),
        # migrations.RemoveField(
        #     model_name='sec',
        #     name='orientation',
        # ),
    ]
