# Generated by Django 2.2 on 2021-07-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_auto_20210720_1549'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='sec',
        #     name='orientation',
        # ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
